export default [
  {
    category: "Спорт",
    type: "Плавание",
    image_path: "src/img/product_photo.jpeg",
    brand: "Joss",
    fullname: "Шапочка для плавания",
    price: 799,
  },
  {
    category: "Одежда",
    type: "Джинсы",
    image_path: "src/img/product_photo.jpeg",
    brand: "Befree",
    fullname: "Джинсы",
    price: 4999,
    size: [34, 35, 36],
  },
  {
    category: "Одежда",
    type: "Джинсы",
    image_path: "src/img/product_photo.jpeg",
    brand: "Cropp",
    fullname: "Джинсы",
    price: 1999,
    newprice: 999,
    size: [38],
  },
  {
    category: "Спорт",
    type: "Скейтборд",
    image_path: "src/img/product_photo.jpeg",
    brand: "Termit",
    fullname: "Скейтборд Cruiser 22",
    price: 2199,
  },
  {
    category: "Обувь",
    type: "Ботинки",
    image_path: "src/img/product_photo.jpeg",
    brand: "PUMA",
    fullname: "Ботинки EXOSTRIDE",
    price: 17990,
    size: [40, 41, 41.5, 42, 43, 43.5],
  },
  {
    category: "Аксессуары",
    type: "Очки",
    image_path: "src/img/product_photo.jpeg",
    brand: "Burberry",
    fullname: "Очки солнцезащитные",
    price: 21800,
  },
  {
    category: "Обувь",
    type: "Ботинки",
    image_path: "src/img/product_photo.jpeg",
    brand: "T.Taccardi",
    fullname: "Ботинки",
    price: 4799,
    newprice: 1499,
    size: [40, 41],
  },
  {
    category: "Обувь",
    type: "Ботинки",
    image_path: "src/img/product_photo.jpeg",
    brand: "Ecco",
    fullname: "Ботинки трекинговые EXOSTRIKE M",
    price: 18990,
    size: [40, 41, 42, 43, 44, 45, 46],
  },
  {
    category: "Обувь",
    type: "Ботинки",
    image_path: "src/img/product_photo.jpeg",
    brand: "Ecco",
    fullname: "Ботинки ST.1 HYBRID",
    price: 18990,
    newprice: 9499,
    size: [40, 41, 41.5, 42, 43],
  },
  {
    category: "Обувь",
    type: "Ботинки",
    image_path: "src/img/product_photo.jpeg",
    brand: "Mascotte",
    fullname: "Ботинки",
    price: 14990,
    newprice: 6690,
    size: [41, 42, 43, 43.5],
  },
  {
    category: "Обувь",
    type: "Ботинки",
    image_path: "src/img/product_photo.jpeg",
    brand: "Alessio Nesca",
    fullname: "Ботинки",
    price: 7499,
    newprice: 4499,
    size: [40],
  },
  {
    category: "Обувь",
    type: "Кроссовки",
    image_path: "src/img/product_photo.jpeg",
    brand: "adidas",
    fullname: "Кроссовки LITE RACER 2.0",
    price: 6399,
    newprice: 3190,
    size: [39, 40, 40.5, 42, 45],
  },
  {
    category: "Обувь",
    type: "Кроссовки",
    image_path: "src/img/product_photo.jpeg",
    brand: "Pulse",
    fullname: "Кеды Полнота D",
    price: 4799,
    size: [42, 43, 44, 44.5, 45],
  },
  {
    category: "Обувь",
    type: "Кроссовки",
    image_path: "src/img/product_photo.jpeg",
    brand: "Reebok",
    fullname: "Кроссовки ROYAL ULTRA",
    price: 7799,
    size: [37.5, 38, 38.5, 39, 40, 40.5, 41, 41.5, 42],
  },
  {
    category: "Обувь",
    type: "Кроссовки",
    image_path: "src/img/product_photo.jpeg",
    brand: "Reebok",
    fullname: "Кроссовки CLASSIC LEATHER",
    price: 10999,
    size: [
      35, 35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 39.5, 40, 40.5, 41, 41.5, 42,
      42.5, 43, 43.5, 44, 45,
    ],
  },
  {
    category: "Обувь",
    type: "Кроссовки",
    image_path: "src/img/product_photo.jpeg",
    brand: "adidas",
    fullname: "Кроссовки SUPERNOVA + M",
    price: 17999,
    newprice: 9890,
    size: [35, 35.5, 36, 36.5, 37, 37.5],
  },
  {
    category: "Обувь",
    type: "Кроссовки",
    image_path: "src/img/product_photo.jpeg",
    brand: "Calvin Klein Jeans",
    fullname: "Кеды",
    price: 15990,
    size: [38, 38.5, 39, 39.5, 40],
  },
  {
    category: "Обувь",
    type: "Кроссовки",
    image_path: "src/img/product_photo.jpeg",
    brand: "New Balance",
    fullname: "Кроссовки Fresh Foam More v4",
    price: 25490,
    size: [39, 40],
  },
  {
    category: "Обувь",
    type: "Кроссовки",
    image_path: "src/img/product_photo.jpeg",
    brand: "PUMA",
    fullname: "Кеды Puma Shuffle Mid Fur",
    price: 8990,
    newprice: 5840,
    size: [36, 36.5, 37, 37.5, 38, 38.5],
  },
  {
    category: "Обувь",
    type: "Кроссовки",
    image_path: "src/img/product_photo.jpeg",
    brand: "Lacoste",
    fullname: "Кеды T-CLIP WNTR 222 2",
    price: 14990,
    size: [40, 40.5, 42],
  },
  {
    category: "Обувь",
    type: "Кроссовки",
    image_path: "src/img/product_photo.jpeg",
    brand: "Tommy Jeans",
    fullname: "Кроссовки",
    price: 13990,
    size: [40, 41, 42],
  },
  {
    category: "Обувь",
    type: "Туфли",
    image_path: "src/img/product_photo.jpeg",
    brand: "Mascotte",
    fullname: "Лоферы",
    price: 14990,
    newprice: 7490,
    size: [
      35, 35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 39.5, 40, 40.5, 41, 41.5, 42,
      42.5, 43, 43.5, 44, 45,
    ],
  },
  {
    category: "Обувь",
    type: "Туфли",
    image_path: "src/img/product_photo.jpeg",
    brand: "Salamander",
    fullname: "Лоферы",
    price: 7490,
    size: [40.5, 41, 41.5, 42, 42.5],
  },
  {
    category: "Обувь",
    type: "Туфли",
    image_path: "src/img/product_photo.jpeg",
    brand: "Alessio Nesca",
    fullname: "Лоферы",
    price: 3390,
    newprice: 1999,
    size: [40, 41, 42, 43, 43.5],
  },
  {
    category: "Обувь",
    type: "Сапоги",
    image_path: "src/img/product_photo.jpeg",
    brand: "Patrol",
    fullname: "Полусапоги",
    price: 9699,
    newprice: 5330,
    size: [43.5, 44, 45],
  },
  {
    category: "Обувь",
    type: "Сапоги",
    image_path: "src/img/product_photo.jpeg",
    brand: "Patrol",
    fullname: "Дутики",
    price: 6890,
    size: [40, 41, 42, 43, 43.5],
  },
  {
    category: "Обувь",
    type: "Сандалии",
    image_path: "src/img/product_photo.jpeg",
    brand: "UNIQLO",
    fullname: "Сабо на липучках",
    price: 2990,
    newprice: 999,
    size: [40, 40.5],
  },
  {
    category: "Обувь",
    type: "Сандалии",
    image_path: "src/img/product_photo.jpeg",
    brand: "Wanngo",
    fullname: "Сандалии",
    price: 4470,
    size: [35, 35.5, 36, 36.5, 42, 42.5],
  },
  {
    category: "Обувь",
    type: "Сандалии",
    image_path: "src/img/product_photo.jpeg",
    brand: "Briggs",
    fullname: "Сандалии",
    price: 5990,
    size: [35, 35.5, 36, 38.5, 39, 39.5, 42],
  },
  {
    category: "Обувь",
    type: "Сандалии",
    image_path: "src/img/product_photo.jpeg",
    brand: "Mascotte",
    fullname: "Сандалии",
    price: 13990,
    size: [39, 39.5, 40, 40.5, 41, 41.5],
  },
  {
    category: "Обувь",
    type: "Сандалии",
    image_path: "src/img/product_photo.jpeg",
    brand: "Alessio Nesca",
    fullname: "Сандалии",
    price: 4373,
    newprice: 2499,
    size: [43, 43.5, 44, 45],
  },
  {
    category: "Обувь",
    type: "Домашняя обувь",
    image_path: "src/img/product_photo.jpeg",
    brand: "UNIQLO",
    fullname: "Тапочки",
    price: 1499,
    size: [
      35, 35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 39.5, 40, 40.5, 41, 41.5, 42,
      42.5, 43, 43.5, 44, 45,
    ],
  },
  {
    category: "Одежда",
    type: "Брюки",
    image_path: "src/img/product_photo.jpeg",
    brand: "UNIQLO",
    fullname: "Брюки SMART",
    price: 3999,
    newprice: 2499,
    size: [42, 44, 46, 48, 50, 52, 54, 56],
  },
  {
    category: "Одежда",
    type: "Брюки",
    image_path: "src/img/product_photo.jpeg",
    brand: "adidas",
    fullname: "Брюки спортивные M 3S FT TC PT",
    price: 5699,
    newprice: 4999,
    size: [50, 52, 54, 56],
  },
  {
    category: "Одежда",
    type: "Брюки",
    image_path: "src/img/product_photo.jpeg",
    brand: "Nike",
    fullname: "Брюки",
    price: 9999,
    size: [42, 44, 46, 48, 50],
  },
  {
    category: "Одежда",
    type: "Брюки",
    image_path: "src/img/product_photo.jpeg",
    brand: "Tommy Hilfiger",
    fullname: "Брюки спортивные",
    price: 9899,
    newprice: 5699,
    size: [42, 44, 46],
  },
  {
    category: "Обувь",
    type: "Ботинки",
    image_path: "src/img/product_photo.jpeg",
    brand: "PUMA",
    fullname: "Ботинки Tarrenz SB II Puretex",
    price: 11490,
    size: [39, 39.5, 40, 41, 41.5, 42],
  },
  {
    category: "Одежда",
    type: "Брюки",
    image_path: "src/img/product_photo.jpeg",
    brand: "O'stin",
    fullname: "Брюки",
    price: 5999,
    size: [42, 44],
  },
  {
    category: "Одежда",
    type: "Брюки",
    image_path: "src/img/product_photo.jpeg",
    brand: "Colin's",
    fullname: "Брюки",
    price: 4099,
    newprice: 3499,
    size: [42, 44, 46, 48, 50, 52, 54, 56],
  },
  {
    category: "Одежда",
    type: "Брюки",
    image_path: "src/img/product_photo.jpeg",
    brand: "adidas",
    fullname: "Брюки спортивные M ZNE PANT",
    price: 9899,
    size: [46, 52, 54, 56],
  },
  {
    category: "Одежда",
    type: "Брюки",
    image_path: "src/img/product_photo.jpeg",
    brand: "Outventure",
    fullname: "Брюки утепленные",
    price: 3999,
    size: [48, 50, 52],
  },
  {
    category: "Одежда",
    type: "Верхняя одежда",
    image_path: "src/img/product_photo.jpeg",
    brand: "UNIQLO",
    fullname: "Пуховик бесшовный с капюшоном",
    price: 14999,
    size: [48, 50, 52],
  },
  {
    category: "Одежда",
    type: "Верхняя одежда",
    image_path: "src/img/product_photo.jpeg",
    brand: "Bask",
    fullname: "Пуховик PUTORANA V3",
    price: 40250,
    size: [44, 46, 48, 50, 52, 54, 56, 58, 60, 62],
  },
  {
    category: "Одежда",
    type: "Верхняя одежда",
    image_path: "src/img/product_photo.jpeg",
    brand: "PUMA",
    fullname: "Куртка утепленная",
    price: 14999,
    newprice: 9199,
    size: [52, 54, 56],
  },
  {
    category: "Одежда",
    type: "Верхняя одежда",
    image_path: "src/img/product_photo.jpeg",
    brand: "Colin's",
    fullname: "Куртка кожаная",
    price: 9990,
    newprice: 4999,
    size: [48],
  },
  {
    category: "Одежда",
    type: "Верхняя одежда",
    image_path: "src/img/product_photo.jpeg",
    brand: "Baon",
    fullname: "Парка",
    price: 12900,
    size: [50, 52],
  },
  {
    category: "Одежда",
    type: "Верхняя одежда",
    image_path: "src/img/product_photo.jpeg",
    brand: "Finn Flare",
    fullname: "Куртка утепленная",
    price: 16999,
    newprice: 10199,
    size: [48, 50, 52, 54],
  },
  {
    category: "Одежда",
    type: "Верхняя одежда",
    image_path: "src/img/product_photo.jpeg",
    brand: "Angelo Bonetti",
    fullname: "Парка MARSHAL",
    price: 20990,
    newprice: 15099,
    size: [52],
  },
  {
    category: "Одежда",
    type: "Свитеры",
    image_path: "src/img/product_photo.jpeg",
    brand: "adidas Originals",
    fullname: "Олимпийка BECKENBAUER TT",
    price: 10990,
    newprice: 4499,
    size: [44, 46, 48, 50],
  },
  {
    category: "Одежда",
    type: "Свитеры",
    image_path: "src/img/product_photo.jpeg",
    brand: "adidas Originals",
    fullname: "Худи TREF OMBRE HD",
    price: 7990,
    newprice: 3599,
    size: [44, 46],
  },
  {
    category: "Одежда",
    type: "Свитеры",
    image_path: "src/img/product_photo.jpeg",
    brand: "Mango Man",
    fullname: "Свитшот NOLA",
    price: 3799,
    size: [52, 54, 56, 58],
  },
  {
    category: "Одежда",
    type: "Свитеры",
    image_path: "src/img/product_photo.jpeg",
    brand: "Lyle & Scott",
    fullname: "Свитшот Crew Neck Sweatshirt",
    price: 4542,
    size: [44, 46],
  },
  {
    category: "Одежда",
    type: "Джинсы",
    image_path: "src/img/product_photo.jpeg",
    brand: "UNIQLO",
    fullname: "Джинсы",
    price: 3999,
    newprice: 2999,
    size: [30, 33, 34, 35, 36, 37, 38],
  },
  {
    category: "Одежда",
    type: "Джинсы",
    image_path: "src/img/product_photo.jpeg",
    brand: "Nike",
    fullname: "Джинсы спортивные",
    price: 5999,
    size: [35, 36, 37, 38],
  },
  {
    category: "Одежда",
    type: "Джинсы",
    image_path: "src/img/product_photo.jpeg",
    brand: "adidas",
    fullname: "Джинсы спортивные",
    price: 7999,
    size: [30, 33, 34, 35, 36, 37, 38],
  },
  {
    category: "Одежда",
    type: "Джинсы",
    image_path: "src/img/product_photo.jpeg",
    brand: "Jlab",
    fullname: "Джинсы трикотажные",
    price: 5899,
    size: [37, 38],
  },
  {
    category: "Одежда",
    type: "Домашняя одежда",
    image_path: "src/img/product_photo.jpeg",
    brand: "Новое Кимоно",
    fullname: "Костюм домашний",
    price: 3799,
    newrice: 3299,
    size: [46, 48, 50, 52, 54],
  },
  {
    category: "Одежда",
    type: "Домашняя одежда",
    image_path: "src/img/product_photo.jpeg",
    brand: "Henderson",
    fullname: "Домашние брюки",
    price: 3999,
    size: [50, 52, 54],
  },
  {
    category: "Одежда",
    type: "Домашняя одежда",
    image_path: "src/img/product_photo.jpeg",
    brand: "Mark Formelle",
    fullname: "Костюм домашний",
    price: 2999,
    newrice: 2561,
    size: [46, 48],
  },
  {
    category: "Одежда",
    type: "Купальники",
    image_path: "src/img/product_photo.jpeg",
    brand: "Helly Hansen",
    fullname: "Шорты для плавания CADIZ TRUNK",
    price: 4490,
    newrice: 2690,
    size: [46, 48],
  },
  {
    category: "Одежда",
    type: "Нижнее бельё",
    image_path: "src/img/product_photo.jpeg",
    brand: "BOSS",
    fullname: "Трусы 3 шт.",
    price: 4000,
    newrice: 3499,
    size: [46, 48, 50, 52, 54],
  },
  {
    category: "Одежда",
    type: "Нижнее бельё",
    image_path: "src/img/product_photo.jpeg",
    brand: "UNIQLO",
    fullname: "Трусы из хлопка SUPIMA",
    price: 599,
    size: [46, 48],
  },
  {
    category: "Одежда",
    type: "Нижнее бельё",
    image_path: "src/img/product_photo.jpeg",
    brand: "Sergio Dallini",
    fullname: "Трусы 3 шт.",
    price: 4900,
    newrice: 2999,
    size: [46, 48, 50, 52, 54],
  },
  {
    category: "Одежда",
    type: "Нижнее бельё",
    image_path: "src/img/product_photo.jpeg",
    brand: "Tommy Hilfiger",
    fullname: "Трусы 3 шт. TRUNK",
    price: 4490,
    size: [52, 54],
  },
  {
    category: "Одежда",
    type: "Нижнее бельё",
    image_path: "src/img/product_photo.jpeg",
    brand: "Springfield",
    fullname: "Трусы 3 шт.",
    price: 2499,
    size: [46, 48, 50, 52, 54],
  },
  {
    category: "Одежда",
    type: "Нижнее бельё",
    image_path: "src/img/product_photo.jpeg",
    brand: "UNIQLO",
    fullname: "Кальсоны HEATTECH С ХЛОПКОМ",
    price: 1999,
    size: [46],
  },
  {
    category: "Одежда",
    type: "Носки",
    image_path: "src/img/product_photo.jpeg",
    brand: "Tezenis",
    fullname: "Носки 5 пар",
    price: 899,
    size: [44],
  },
  {
    category: "Одежда",
    type: "Носки",
    image_path: "src/img/product_photo.jpeg",
    brand: "Henderson",
    fullname: "Носки",
    price: 299,
    size: [46],
  },
  {
    category: "Одежда",
    type: "Носки",
    image_path: "src/img/product_photo.jpeg",
    brand: "oodji",
    fullname: "Носки 10 пар",
    price: 999,
    size: [48],
  },
  {
    category: "Одежда",
    type: "Шорты",
    image_path: "src/img/product_photo.jpeg",
    brand: "Demix",
    fullname: "Шорты спортивные",
    price: 1299,
    newrice: 999,
    size: [46, 48, 50, 52, 54],
  },
  {
    category: "Одежда",
    type: "Шорты",
    image_path: "src/img/product_photo.jpeg",
    brand: "UNIQLO",
    fullname: "Шорты чинос",
    price: 1999,
    size: [50, 52, 54],
  },
  {
    category: "Одежда",
    type: "Шорты",
    image_path: "src/img/product_photo.jpeg",
    brand: "Aeronautica Militare",
    fullname: "Шорты спортивные",
    price: 13600,
    size: [46, 48, 50, 52, 54, 56],
  },
  {
    category: "Одежда",
    type: "Шорты",
    image_path: "src/img/product_photo.jpeg",
    brand: "United Colors of Benetton",
    fullname: "Шорты",
    price: 6599,
    newprice: 3390,
    size: [44, 46],
  },
  {
    category: "Одежда",
    type: "Шорты",
    image_path: "src/img/product_photo.jpeg",
    brand: "Envylab",
    fullname: "Шорты спортивные",
    price: 2290,
    newprice: 1590,
    size: [44, 48, 54],
  },
  {
    category: "Одежда",
    type: "Шорты",
    image_path: "src/img/product_photo.jpeg",
    brand: "O'stin",
    fullname: "Шорты джинсовые",
    price: 2599,
    size: [50, 52],
  },
  {
    category: "Одежда",
    type: "Юбки",
    image_path: "src/img/product_photo.jpeg",
    brand: "Love Republic",
    fullname: "Юбка",
    price: 1990,
    newprice: 1199,
    size: [40, 42, 44, 46, 48],
  },
  {
    category: "Одежда",
    type: "Юбки",
    image_path: "src/img/product_photo.jpeg",
    brand: "Mango",
    fullname: "Юбка PAROS",
    price: 7999,
    size: [44, 46, 48],
  },
  {
    category: "Одежда",
    type: "Юбки",
    image_path: "src/img/product_photo.jpeg",
    brand: "Sela",
    fullname: "Юбка",
    price: 3990,
    newprice: 1499,
    size: [40, 42],
  },
  {
    category: "Одежда",
    type: "Юбки",
    image_path: "src/img/product_photo.jpeg",
    brand: "Love Republic",
    fullname: "Юбка",
    price: 2990,
    size: [40, 42, 44, 46, 48],
  },
  {
    category: "Одежда",
    type: "Юбки",
    image_path: "src/img/product_photo.jpeg",
    brand: "Befree",
    fullname: "Юбка",
    price: 2990,
    newprice: 1699,
    size: [44, 46],
  },
  {
    category: "Одежда",
    type: "Юбки",
    image_path: "src/img/product_photo.jpeg",
    brand: "Fadjo",
    fullname: "Юбка",
    price: 5990,
    newprice: 4999,
    size: [42, 44, 48],
  },
  {
    category: "Одежда",
    type: "Юбки",
    image_path: "src/img/product_photo.jpeg",
    brand: "Mossmore",
    fullname: "Юбка джинсовая",
    price: 7990,
    newprice: 4699,
    size: [40],
  },
  {
    category: "Одежда",
    type: "Юбки",
    image_path: "src/img/product_photo.jpeg",
    brand: "Zarina",
    fullname: "Юбка",
    price: 1490,
    size: [40, 42, 44, 46, 48],
  },
  {
    category: "Одежда",
    type: "Юбки",
    image_path: "src/img/product_photo.jpeg",
    brand: "Nominee",
    fullname: "Юбка",
    price: 4999,
    newprice: 2999,
    size: [40, 44],
  },
  {
    category: "Аксессуары",
    type: "Головные уборы",
    image_path: "src/img/product_photo.jpeg",
    brand: "Karl Lagerfeld",
    fullname: "Шапка IKONIK",
    price: 8900,
    newprice: 5990,
  },
  {
    category: "Аксессуары",
    type: "Головные уборы",
    image_path: "src/img/product_photo.jpeg",
    brand: "Patrizia Pepe",
    fullname: "Бейсболка",
    price: 5600,
  },
  {
    category: "Аксессуары",
    type: "Головные уборы",
    image_path: "src/img/product_photo.jpeg",
    brand: "Moschino",
    fullname: "Шапка",
    price: 9290,
    newprice: 6599,
  },
  {
    category: "Аксессуары",
    type: "Головные уборы",
    image_path: "src/img/product_photo.jpeg",
    brand: "Weekend Max Mara",
    fullname: "Шапка ALBEN",
    price: 11999,
    newprice: 8800,
  },
  {
    category: "Аксессуары",
    type: "Головные уборы",
    image_path: "src/img/product_photo.jpeg",
    brand: "Hugo",
    fullname: "Шапка",
    price: 6000,
  },
  {
    category: "Аксессуары",
    type: "Зонты",
    image_path: "src/img/product_photo.jpeg",
    brand: "Karl Lagerfeld",
    fullname: "Зонт складной",
    price: 4500,
  },
  {
    category: "Аксессуары",
    type: "Зонты",
    image_path: "src/img/product_photo.jpeg",
    brand: "Samsonite",
    fullname: "Зонт складной",
    price: 3500,
  },
  {
    category: "Аксессуары",
    type: "Зонты",
    image_path: "src/img/product_photo.jpeg",
    brand: "Labbra",
    fullname: "Зонт складной",
    price: 3410,
    newprice: 1920,
  },
  {
    category: "Аксессуары",
    type: "Канцелярские товары",
    image_path: "src/img/product_photo.jpeg",
    brand: "Parker",
    fullname: "Ручка",
    price: 3910,
    newprice: 2421,
  },
  {
    category: "Аксессуары",
    type: "Канцелярские товары",
    image_path: "src/img/product_photo.jpeg",
    brand: "Moleskine",
    fullname: "Блокнот CLASSIC Large",
    price: 1799,
  },
  {
    category: "Аксессуары",
    type: "Канцелярские товары",
    image_path: "src/img/product_photo.jpeg",
    brand: "Deli",
    fullname: "Органайзер для хранения",
    price: 890,
  },
  {
    category: "Аксессуары",
    type: "Рюкзаки",
    image_path: "src/img/product_photo.jpeg",
    brand: "Karl Lagerfeld",
    fullname: "Рюкзак IKONIK",
    price: 33900,
    newprice: 17500,
  },
  {
    category: "Аксессуары",
    type: "Рюкзаки",
    image_path: "src/img/product_photo.jpeg",
    brand: "Michael Michael Kors",
    fullname: "Рюкзак",
    price: 36900,
  },
  {
    category: "Аксессуары",
    type: "Сумки",
    image_path: "src/img/product_photo.jpeg",
    brand: "Karl Lagerfeld",
    fullname: "Сумка IKONIK",
    price: 7200,
  },
  {
    category: "Аксессуары",
    type: "Сумки",
    image_path: "src/img/product_photo.jpeg",
    brand: "Tervolina",
    fullname: "Сумка",
    price: 17200,
    newprice: 10782,
  },
  {
    category: "Аксессуары",
    type: "Сумки",
    image_path: "src/img/product_photo.jpeg",
    brand: "Furla",
    fullname: "Сумка FURLA VARSITY STYLE",
    price: 43000,
  },
  {
    category: "Спорт",
    type: "Велоспорт",
    image_path: "src/img/product_photo.jpeg",
    brand: "Profit",
    fullname: "Тайтсы пуш-ап",
    price: 5490,
    newprice: 3290,
    size: [46, 48],
  },
  {
    category: "Спорт",
    type: "Велоспорт",
    image_path: "src/img/product_photo.jpeg",
    brand: "Profit",
    fullname: "Топ",
    price: 2690,
    newprice: 2190,
    size: [44, 46, 48],
  },
  {
    category: "Спорт",
    type: "Велоспорт",
    image_path: "src/img/product_photo.jpeg",
    brand: "Profit",
    fullname: "Тайтсы пуш-ап",
    price: 5490,
    newprice: 3290,
    size: [46, 48],
  },
  {
    category: "Спорт",
    type: "Велоспорт",
    image_path: "src/img/product_photo.jpeg",
    brand: "Euphoria",
    fullname: "Шорты спортивные Classic",
    price: 4200,
    newprice: 2500,
    size: [40, 42, 44, 46, 48],
  },
  {
    category: "Спорт",
    type: "Велоспорт",
    image_path: "src/img/product_photo.jpeg",
    brand: "Gympanthers",
    fullname: "Велосипедки Gympanthers Original",
    price: 4200,
    size: [42],
  },
  {
    category: "Спорт",
    type: "Велоспорт",
    image_path: "src/img/product_photo.jpeg",
    brand: "Euphoria",
    fullname: "Леггинсы",
    price: 6799,
    newprice: 1380,
    size: [48],
  },
  {
    category: "Спорт",
    type: "Скейтборд",
    image_path: "src/img/product_photo.jpeg",
    brand: "Roces",
    fullname: "Скейтборд Indian",
    price: 6299,
  },
  {
    category: "Спорт",
    type: "Скейтборд",
    image_path: "src/img/product_photo.jpeg",
    brand: "Termit",
    fullname: "Скейтборд 22",
    price: 1199,
  },
  {
    category: "Спорт",
    type: "Футбол",
    image_path: "src/img/product_photo.jpeg",
    brand: "Nike",
    fullname: "Мяч футбольный PL NK PTCH-FA19",
    price: 760,
  },
  {
    category: "Спорт",
    type: "Футбол",
    image_path: "src/img/product_photo.jpeg",
    brand: "adidas",
    fullname: "Мяч футбольный CNXT21 TRN",
    price: 3100,
    newprice: 2499,
  },
  {
    category: "Спорт",
    type: "Футбол",
    image_path: "src/img/product_photo.jpeg",
    brand: "Molten",
    fullname: "Мяч футбольный",
    price: 3500,
  },
  {
    category: "Спорт",
    type: "Фитнес",
    image_path: "src/img/product_photo.jpeg",
    brand: "adidas",
    fullname: "Бутылка PERF BTTL 0,5",
    price: 650,
  },
  {
    category: "Спорт",
    type: "Фитнес",
    image_path: "src/img/product_photo.jpeg",
    brand: "Prorun",
    fullname: "Гантели",
    price: 599,
  },
  {
    category: "Красота",
    type: "Макияж",
    image_path: "src/img/product_photo.jpeg",
    brand: "Clarins",
    fullname: "Набор косметики",
    price: 2230,
    newprice: 1673,
  },
  {
    category: "Красота",
    type: "Макияж",
    image_path: "src/img/product_photo.jpeg",
    brand: "Vivienne Sabo",
    fullname: "Тушь для ресниц",
    price: 560,
    newprice: 476,
  },
  {
    category: "Красота",
    type: "Макияж",
    image_path: "src/img/product_photo.jpeg",
    brand: "Physicians Formula",
    fullname: "Палетка для лица",
    price: 2060,
  },
  {
    category: "Красота",
    type: "Для ванны и душа",
    image_path: "src/img/product_photo.jpeg",
    brand: "Yves Rocher",
    fullname: "Гель для душа",
    price: 460,
  },
  {
    category: "Красота",
    type: "Для ванны и душа",
    image_path: "src/img/product_photo.jpeg",
    brand: "Yves Rocher",
    fullname: "Гель для душа",
    price: 580,
  },
  {
    category: "Красота",
    type: "Для ванны и душа",
    image_path: "src/img/product_photo.jpeg",
    brand: "SeaCare",
    fullname: "Скраб",
    price: 2100,
    newprice: 1209,
  },
  {
    category: "Красота",
    type: "Волосы",
    image_path: "src/img/product_photo.jpeg",
    brand: "Grace and Stella",
    fullname: "Набор для ухода за волосами",
    price: 3050,
    newprice: 1200,
  },
  {
    category: "Красота",
    type: "Волосы",
    image_path: "src/img/product_photo.jpeg",
    brand: "Vichy",
    fullname: "Бальзам для волос",
    price: 1930,
    newprice: 1425,
  },
  {
    category: "Красота",
    type: "Маникюр и педикюр",
    image_path: "src/img/product_photo.jpeg",
    brand: "Eveline Cosmetics",
    fullname: "Средство для укрепления ногтей",
    price: 270,
  },
  {
    category: "Красота",
    type: "Маникюр и педикюр",
    image_path: "src/img/product_photo.jpeg",
    brand: "Anny",
    fullname: "Лак для ногтей",
    price: 640,
  },
  {
    category: "Красота",
    type: "Маникюр и педикюр",
    image_path: "src/img/product_photo.jpeg",
    brand: "Olzori",
    fullname: "Пилка для педикюра",
    price: 1590,
    newprice: 990,
  },
  {
    category: "Красота",
    type: "Маникюр и педикюр",
    image_path: "src/img/product_photo.jpeg",
    brand: "Metaleks",
    fullname: "Кусачки для маникюра",
    price: 1200,
  },
  {
    category: "Красота",
    type: "Маникюр и педикюр",
    image_path: "src/img/product_photo.jpeg",
    brand: "Victorinox",
    fullname: "Набор маникюрный",
    price: 7800,
    newprice: 5000,
  }
];
