import { defineStore } from "pinia";
import { addItemLS, downloadFromLS } from "./localStorage";

function checkDuplicate(productIN, productOUT) {
  return (
    productIN.id === productOUT.id &&
    productIN.color === productOUT.color &&
    productIN?.sizeSelected === productOUT?.sizeSelected
  );
}

export const useProductsStore = defineStore("productsStore", {
  state: () => ({
    products: [
      {
        id: 1,
        category: "Спорт",
        type: "Плавание",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Joss",
        fullname: "Шапочка для плавания",
        price: 799,
        colors: ["Черный", "Белый"],
      },
      {
        id: 2,
        category: "Одежда",
        type: "Джинсы",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Befree",
        fullname: "Джинсы",
        price: 4999,
        size: [34, 35, 36],
        colors: ["Черный", "Белый", "Серый", "Синий"],
      },
      {
        id: 3,
        category: "Одежда",
        type: "Джинсы",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Cropp",
        fullname: "Джинсы",
        price: 1999,
        newprice: 999,
        size: [38],
        colors: ["Синий", "Красный", "Розовый", "Зеленый", "Желтый"],
      },
      {
        id: 4,
        category: "Спорт",
        type: "Скейтборд",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Termit",
        fullname: "Скейтборд Cruiser 22",
        price: 2199,
        colors: ["Черный", "Белый", "Синий"],
      },
      {
        id: 5,
        category: "Обувь",
        type: "Ботинки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "PUMA",
        fullname: "Ботинки EXOSTRIDE",
        price: 17990,
        size: [40, 41, 41.5, 42, 43, 43.5],
        colors: ["Розовый", "Зеленый", "Желтый"],
      },
      {
        id: 7,
        category: "Обувь",
        type: "Ботинки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "T.Taccardi",
        fullname: "Ботинки",
        price: 4799,
        newprice: 1499,
        size: [40, 41],
        colors: ["Желтый"],
      },
      {
        id: 8,
        category: "Обувь",
        type: "Ботинки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Ecco",
        fullname: "Ботинки трекинговые EXOSTRIKE M",
        price: 18990,
        size: [40, 41, 42, 43, 44, 45, 46],
        colors: ["Черный"],
      },
      {
        id: 9,
        category: "Обувь",
        type: "Ботинки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Ecco",
        fullname: "Ботинки ST.1 HYBRID",
        price: 18990,
        newprice: 9499,
        size: [40, 41, 41.5, 42, 43],
        colors: ["Желтый"],
      },
      {
        id: 10,
        category: "Обувь",
        type: "Ботинки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Mascotte",
        fullname: "Ботинки",
        price: 14990,
        newprice: 6690,
        size: [41, 42, 43, 43.5],
        colors: ["Черный", "Синий", "Желтый"],
      },
      {
        id: 11,
        category: "Обувь",
        type: "Ботинки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Alessio Nesca",
        fullname: "Ботинки",
        price: 7499,
        newprice: 4499,
        size: [40],
        colors: ["Черный", "Белый", "Розовый", "Зеленый", "Желтый"],
      },
      {
        id: 12,
        category: "Обувь",
        type: "Кроссовки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "adidas",
        fullname: "Кроссовки LITE RACER 2.0",
        price: 6399,
        newprice: 3190,
        size: [39, 40, 40.5, 42, 45],
        colors: ["Черный", "Белый"],
      },
      {
        id: 13,
        category: "Обувь",
        type: "Кроссовки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Pulse",
        fullname: "Кеды Полнота D",
        price: 4799,
        size: [42, 43, 44, 44.5, 45],
        colors: ["Черный", "Белый", "Серый", "Синий"],
      },
      {
        id: 14,
        category: "Обувь",
        type: "Кроссовки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Reebok",
        fullname: "Кроссовки ROYAL ULTRA",
        price: 7799,
        size: [37.5, 38, 38.5, 39, 40, 40.5, 41, 41.5, 42],
        colors: ["Черный", "Белый", "Серый", "Зеленый", "Желтый"],
      },
      {
        id: 15,
        category: "Обувь",
        type: "Кроссовки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Reebok",
        fullname: "Кроссовки CLASSIC LEATHER",
        price: 10999,
        size: [
          35, 35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 39.5, 40, 40.5, 41, 41.5,
          42, 42.5, 43, 43.5, 44, 45,
        ],
        colors: ["Черный", "Желтый"],
      },
      {
        id: 16,
        category: "Обувь",
        type: "Кроссовки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "adidas",
        fullname: "Кроссовки SUPERNOVA + M",
        price: 17999,
        newprice: 9890,
        size: [35, 35.5, 36, 36.5, 37, 37.5],
        colors: ["Зеленый", "Желтый"],
      },
      {
        id: 17,
        category: "Обувь",
        type: "Кроссовки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Calvin Klein Jeans",
        fullname: "Кеды",
        price: 15990,
        size: [38, 38.5, 39, 39.5, 40],
        colors: ["Черный", "Белый"],
      },
      {
        id: 18,
        category: "Обувь",
        type: "Кроссовки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "New Balance",
        fullname: "Кроссовки Fresh Foam More v4",
        price: 25490,
        size: [39, 40],
        colors: ["Черный", "Белый"],
      },
      {
        id: 19,
        category: "Обувь",
        type: "Кроссовки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "PUMA",
        fullname: "Кеды Puma Shuffle Mid Fur",
        price: 8990,
        newprice: 5840,
        size: [36, 36.5, 37, 37.5, 38, 38.5],
        colors: ["Черный", "Зеленый"],
      },
      {
        id: 20,
        category: "Обувь",
        type: "Кроссовки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Lacoste",
        fullname: "Кеды T-CLIP WNTR 222 2",
        price: 14990,
        size: [40, 40.5, 42],
        colors: ["Розовый"],
      },
      {
        id: 21,
        category: "Обувь",
        type: "Кроссовки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Tommy Jeans",
        fullname: "Кроссовки",
        price: 13990,
        size: [40, 41, 42],
        colors: ["Серый", "Синий"],
      },
      {
        id: 22,
        category: "Обувь",
        type: "Туфли",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Mascotte",
        fullname: "Лоферы",
        price: 14990,
        newprice: 7490,
        size: [
          35, 35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 39.5, 40, 40.5, 41, 41.5,
          42, 42.5, 43, 43.5, 44, 45,
        ],
        colors: ["Синий", "Красный"],
      },
      {
        id: 23,
        category: "Обувь",
        type: "Туфли",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Salamander",
        fullname: "Лоферы",
        price: 7490,
        size: [40.5, 41, 41.5, 42, 42.5],
        colors: ["Черный", "Белый"],
      },
      {
        id: 24,
        category: "Обувь",
        type: "Туфли",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Alessio Nesca",
        fullname: "Лоферы",
        price: 3390,
        newprice: 1999,
        size: [40, 41, 42, 43, 43.5],
        colors: ["Черный", "Зеленый", "Желтый"],
      },
      {
        id: 25,
        category: "Обувь",
        type: "Сапоги",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Patrol",
        fullname: "Полусапоги",
        price: 9699,
        newprice: 5330,
        size: [43.5, 44, 45],
        colors: ["Черный", "Белый", "Желтый"],
      },
      {
        id: 26,
        category: "Обувь",
        type: "Сапоги",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Patrol",
        fullname: "Дутики",
        price: 6890,
        size: [40, 41, 42, 43, 43.5],
        colors: ["Красный", "Розовый", "Зеленый", "Желтый"],
      },
      {
        id: 27,
        category: "Обувь",
        type: "Сандалии",
        image_path: "/src/assets/images/product_photo.png",
        brand: "UNIQLO",
        fullname: "Сабо на липучках",
        price: 2990,
        newprice: 999,
        size: [40, 40.5],
        colors: ["Черный", "Красный", "Розовый", "Желтый"],
      },
      {
        id: 28,
        category: "Обувь",
        type: "Сандалии",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Wanngo",
        fullname: "Сандалии",
        price: 4470,
        size: [35, 35.5, 36, 36.5, 42, 42.5],
        colors: ["Черный", "Белый", "Желтый"],
      },
      {
        id: 29,
        category: "Обувь",
        type: "Сандалии",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Briggs",
        fullname: "Сандалии",
        price: 5990,
        size: [35, 35.5, 36, 38.5, 39, 39.5, 42],
        colors: ["Черный", "Розовый", "Желтый"],
      },
      {
        id: 30,
        category: "Обувь",
        type: "Сандалии",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Mascotte",
        fullname: "Сандалии",
        price: 13990,
        size: [39, 39.5, 40, 40.5, 41, 41.5],
        colors: ["Синий", "Красный"],
      },
      {
        id: 31,
        category: "Обувь",
        type: "Сандалии",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Alessio Nesca",
        fullname: "Сандалии",
        price: 4373,
        newprice: 2499,
        size: [43, 43.5, 44, 45],
        colors: ["Красный", "Желтый"],
      },
      {
        id: 32,
        category: "Обувь",
        type: "Домашняя обувь",
        image_path: "/src/assets/images/product_photo.png",
        brand: "UNIQLO",
        fullname: "Тапочки",
        price: 1499,
        size: [
          35, 35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 39.5, 40, 40.5, 41, 41.5,
          42, 42.5, 43, 43.5, 44, 45,
        ],
        colors: ["Черный", "Розовый", "Зеленый", "Желтый"],
      },
      {
        id: 33,
        category: "Одежда",
        type: "Брюки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "UNIQLO",
        fullname: "Брюки SMART",
        price: 3999,
        newprice: 2499,
        size: [42, 44, 46, 48, 50, 52, 54, 56],
        colors: ["Черный"],
      },
      {
        id: 34,
        category: "Одежда",
        type: "Брюки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "adidas",
        fullname: "Брюки спортивные M 3S FT TC PT",
        price: 5699,
        newprice: 4999,
        size: [50, 52, 54, 56],
        colors: ["Белый"],
      },
      {
        id: 35,
        category: "Одежда",
        type: "Брюки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Nike",
        fullname: "Брюки",
        price: 9999,
        size: [42, 44, 46, 48, 50],
        colors: ["Черный"],
      },
      {
        id: 36,
        category: "Одежда",
        type: "Брюки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Tommy Hilfiger",
        fullname: "Брюки спортивные",
        price: 9899,
        newprice: 5699,
        size: [42, 44, 46],
        colors: ["Черный"],
      },
      {
        id: 37,
        category: "Обувь",
        type: "Ботинки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "PUMA",
        fullname: "Ботинки Tarrenz SB II Puretex",
        price: 11490,
        size: [39, 39.5, 40, 41, 41.5, 42],
        colors: ["Синий"],
      },
      {
        id: 38,
        category: "Одежда",
        type: "Брюки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "O'stin",
        fullname: "Брюки",
        price: 5999,
        size: [42, 44],
        colors: ["Розовый"],
      },
      {
        id: 39,
        category: "Одежда",
        type: "Брюки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Colin's",
        fullname: "Брюки",
        price: 4099,
        newprice: 3499,
        size: [42, 44, 46, 48, 50, 52, 54, 56],
        colors: ["Розовый"],
      },
      {
        id: 40,
        category: "Одежда",
        type: "Брюки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "adidas",
        fullname: "Брюки спортивные M ZNE PANT",
        price: 9899,
        size: [46, 52, 54, 56],
        colors: ["Серый", "Синий"],
      },
      {
        id: 41,
        category: "Одежда",
        type: "Брюки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Outventure",
        fullname: "Брюки утепленные",
        price: 3999,
        size: [48, 50, 52],
        colors: ["Красный", "Розовый"],
      },
      {
        id: 42,
        category: "Одежда",
        type: "Верхняя одежда",
        image_path: "/src/assets/images/product_photo.png",
        brand: "UNIQLO",
        fullname: "Пуховик бесшовный с капюшоном",
        price: 14999,
        size: [48, 50, 52],
        colors: ["Серый", "Синий", "Красный"],
      },
      {
        id: 43,
        category: "Одежда",
        type: "Верхняя одежда",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Bask",
        fullname: "Пуховик PUTORANA V3",
        price: 40250,
        size: [44, 46, 48, 50, 52, 54, 56, 58, 60, 62],
        colors: ["Белый"],
      },
      {
        id: 44,
        category: "Одежда",
        type: "Верхняя одежда",
        image_path: "/src/assets/images/product_photo.png",
        brand: "PUMA",
        fullname: "Куртка утепленная",
        price: 14999,
        newprice: 9199,
        size: [52, 54, 56],
        colors: ["Белый", "Серый"],
      },
      {
        id: 45,
        category: "Одежда",
        type: "Верхняя одежда",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Colin's",
        fullname: "Куртка кожаная",
        price: 9990,
        newprice: 4999,
        size: [48],
        colors: ["Серый"],
      },
      {
        id: 46,
        category: "Одежда",
        type: "Верхняя одежда",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Baon",
        fullname: "Парка",
        price: 12900,
        size: [50, 52],
        colors: ["Серый"],
      },
      {
        id: 47,
        category: "Одежда",
        type: "Верхняя одежда",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Finn Flare",
        fullname: "Куртка утепленная",
        price: 16999,
        newprice: 10199,
        size: [48, 50, 52, 54],
        colors: ["Синий"],
      },
      {
        id: 48,
        category: "Одежда",
        type: "Верхняя одежда",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Angelo Bonetti",
        fullname: "Парка MARSHAL",
        price: 20990,
        newprice: 15099,
        size: [52],
        colors: ["Розовый"],
      },
      {
        id: 49,
        category: "Одежда",
        type: "Свитеры",
        image_path: "/src/assets/images/product_photo.png",
        brand: "adidas Originals",
        fullname: "Олимпийка BECKENBAUER TT",
        price: 10990,
        newprice: 4499,
        size: [44, 46, 48, 50],
        colors: ["Черный"],
      },
      {
        id: 50,
        category: "Одежда",
        type: "Свитеры",
        image_path: "/src/assets/images/product_photo.png",
        brand: "adidas Originals",
        fullname: "Худи TREF OMBRE HD",
        price: 7990,
        newprice: 3599,
        size: [44, 46],
        colors: ["Белый", "Серый"],
      },
      {
        id: 51,
        category: "Одежда",
        type: "Свитеры",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Mango Man",
        fullname: "Свитшот NOLA",
        price: 3799,
        size: [52, 54, 56, 58],
        colors: [
          "Черный",
          "Белый",
          "Серый",
          "Синий",
          "Красный",
          "Розовый",
          "Зеленый",
          "Желтый",
        ],
      },
      {
        id: 52,
        category: "Одежда",
        type: "Свитеры",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Lyle & Scott",
        fullname: "Свитшот Crew Neck Sweatshirt",
        price: 4542,
        size: [44, 46],
        colors: [
          "Черный",
          "Белый",
          "Серый",
          "Синий",
          "Красный",
          "Розовый",
          "Зеленый",
          "Желтый",
        ],
      },
      {
        id: 53,
        category: "Одежда",
        type: "Джинсы",
        image_path: "/src/assets/images/product_photo.png",
        brand: "UNIQLO",
        fullname: "Джинсы",
        price: 3999,
        newprice: 2999,
        size: [30, 33, 34, 35, 36, 37, 38],
        colors: ["Черный", "Белый", "Серый"],
      },
      {
        id: 54,
        category: "Одежда",
        type: "Джинсы",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Nike",
        fullname: "Джинсы спортивные",
        price: 5999,
        size: [35, 36, 37, 38],
        colors: ["Серый"],
      },
      {
        id: 55,
        category: "Одежда",
        type: "Джинсы",
        image_path: "/src/assets/images/product_photo.png",
        brand: "adidas",
        fullname: "Джинсы спортивные",
        price: 7999,
        size: [30, 33, 34, 35, 36, 37, 38],
        colors: ["Серый"],
      },
      {
        id: 56,
        category: "Одежда",
        type: "Джинсы",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Jlab",
        fullname: "Джинсы трикотажные",
        price: 5899,
        size: [37, 38],
        colors: ["Черный"],
      },
      {
        id: 57,
        category: "Одежда",
        type: "Домашняя одежда",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Новое Кимоно",
        fullname: "Костюм домашний",
        price: 3799,
        newrice: 3299,
        size: [46, 48, 50, 52, 54],
        colors: [
          "Черный",
          "Белый",
          "Серый",
          "Синий",
          "Красный",
          "Розовый",
          "Зеленый",
          "Желтый",
        ],
      },
      {
        id: 58,
        category: "Одежда",
        type: "Домашняя одежда",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Henderson",
        fullname: "Домашние брюки",
        price: 3999,
        size: [50, 52, 54],
        colors: ["Черный", "Белый", "Серый", "Синий", "Красный"],
      },
      {
        id: 59,
        category: "Одежда",
        type: "Домашняя одежда",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Mark Formelle",
        fullname: "Костюм домашний",
        price: 2999,
        newrice: 2561,
        size: [46, 48],
        colors: [
          "Черный",
          "Белый",
          "Серый",
          "Синий",
          "Красный",
          "Розовый",
          "Зеленый",
          "Желтый",
        ],
      },
      {
        id: 60,
        category: "Одежда",
        type: "Купальники",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Helly Hansen",
        fullname: "Шорты для плавания CADIZ TRUNK",
        price: 4490,
        newrice: 2690,
        size: [46, 48],
        colors: ["Розовый", "Зеленый", "Желтый"],
      },
      {
        id: 61,
        category: "Одежда",
        type: "Нижнее белье",
        image_path: "/src/assets/images/product_photo.png",
        brand: "BOSS",
        fullname: "Трусы 3 шт.",
        price: 4000,
        newrice: 3499,
        size: [46, 48, 50, 52, 54],
        colors: ["Черный", "Белый", "Серый"],
      },
      {
        id: 62,
        category: "Одежда",
        type: "Нижнее белье",
        image_path: "/src/assets/images/product_photo.png",
        brand: "UNIQLO",
        fullname: "Трусы из хлопка SUPIMA",
        price: 599,
        size: [46, 48],
        colors: ["Черный", "Белый", "Серый", "Красный"],
      },
      {
        id: 63,
        category: "Одежда",
        type: "Нижнее белье",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Sergio Dallini",
        fullname: "Трусы 3 шт.",
        price: 4900,
        newrice: 2999,
        size: [46, 48, 50, 52, 54],
        colors: ["Черный", "Зеленый", "Желтый"],
      },
      {
        id: 64,
        category: "Одежда",
        type: "Нижнее белье",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Tommy Hilfiger",
        fullname: "Трусы 3 шт. TRUNK",
        price: 4490,
        size: [52, 54],
        colors: ["Черный", "Синий", "Красный"],
      },
      {
        id: 65,
        category: "Одежда",
        type: "Нижнее белье",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Springfield",
        fullname: "Трусы 3 шт.",
        price: 2499,
        size: [46, 48, 50, 52, 54],
        colors: ["Черный"],
      },
      {
        id: 66,
        category: "Одежда",
        type: "Нижнее белье",
        image_path: "/src/assets/images/product_photo.png",
        brand: "UNIQLO",
        fullname: "Кальсоны HEATTECH С ХЛОПКОМ",
        price: 1999,
        size: [46],
        colors: ["Черный", "Белый"],
      },
      {
        id: 67,
        category: "Одежда",
        type: "Носки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Tezenis",
        fullname: "Носки 5 пар",
        price: 899,
        size: [44],
        colors: [
          "Черный",
          "Белый",
          "Серый",
          "Синий",
          "Красный",
          "Розовый",
          "Зеленый",
          "Желтый",
        ],
      },
      {
        id: 68,
        category: "Одежда",
        type: "Носки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Henderson",
        fullname: "Носки",
        price: 299,
        size: [46],
        colors: [
          "Черный",
          "Белый",
          "Серый",
          "Синий",
          "Красный",
          "Розовый",
          "Зеленый",
          "Желтый",
        ],
      },
      {
        id: 69,
        category: "Одежда",
        type: "Носки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "oodji",
        fullname: "Носки 10 пар",
        price: 999,
        size: [48],
        colors: [
          "Черный",
          "Белый",
          "Серый",
          "Синий",
          "Красный",
          "Розовый",
          "Зеленый",
          "Желтый",
        ],
      },
      {
        id: 70,
        category: "Одежда",
        type: "Шорты",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Demix",
        fullname: "Шорты спортивные",
        price: 1299,
        newrice: 999,
        size: [46, 48, 50, 52, 54],
        colors: ["Черный", "Белый", "Серый"],
      },
      {
        id: 71,
        category: "Одежда",
        type: "Шорты",
        image_path: "/src/assets/images/product_photo.png",
        brand: "UNIQLO",
        fullname: "Шорты чинос",
        price: 1999,
        size: [50, 52, 54],
        colors: ["Черный", "Белый", "Серый"],
      },
      {
        id: 72,
        category: "Одежда",
        type: "Шорты",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Aeronautica Militare",
        fullname: "Шорты спортивные",
        price: 13600,
        size: [46, 48, 50, 52, 54, 56],
        colors: ["Серый"],
      },
      {
        id: 73,
        category: "Одежда",
        type: "Шорты",
        image_path: "/src/assets/images/product_photo.png",
        brand: "United Colors of Benetton",
        fullname: "Шорты",
        price: 6599,
        newprice: 3390,
        size: [44, 46],
        colors: ["Зеленый", "Желтый"],
      },
      {
        id: 74,
        category: "Одежда",
        type: "Шорты",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Envylab",
        fullname: "Шорты спортивные",
        price: 2290,
        newprice: 1590,
        size: [44, 48, 54],
        colors: ["Черный", "Белый"],
      },
      {
        id: 75,
        category: "Одежда",
        type: "Шорты",
        image_path: "/src/assets/images/product_photo.png",
        brand: "O'stin",
        fullname: "Шорты джинсовые",
        price: 2599,
        size: [50, 52],
        colors: ["Синий"],
      },
      {
        id: 76,
        category: "Одежда",
        type: "Юбки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Love Republic",
        fullname: "Юбка",
        price: 1990,
        newprice: 1199,
        size: [40, 42, 44, 46, 48],
        colors: [
          "Черный",
          "Белый",
          "Серый",
          "Синий",
          "Красный",
          "Розовый",
          "Зеленый",
          "Желтый",
        ],
      },
      {
        id: 77,
        category: "Одежда",
        type: "Юбки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Mango",
        fullname: "Юбка PAROS",
        price: 7999,
        size: [44, 46, 48],
        colors: ["Черный", "Розовый", "Зеленый"],
      },
      {
        id: 78,
        category: "Одежда",
        type: "Юбки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Sela",
        fullname: "Юбка",
        price: 3990,
        newprice: 1499,
        size: [40, 42],
        colors: ["Розовый"],
      },
      {
        id: 79,
        category: "Одежда",
        type: "Юбки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Love Republic",
        fullname: "Юбка",
        price: 2990,
        size: [40, 42, 44, 46, 48],
        colors: ["Красный"],
      },
      {
        id: 80,
        category: "Одежда",
        type: "Юбки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Befree",
        fullname: "Юбка",
        price: 2990,
        newprice: 1699,
        size: [44, 46],
        colors: ["Красный", "Розовый"],
      },
      {
        id: 81,
        category: "Одежда",
        type: "Юбки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Fadjo",
        fullname: "Юбка",
        price: 5990,
        newprice: 4999,
        size: [42, 44, 48],
        colors: ["Черный", "Зеленый", "Желтый"],
      },
      {
        id: 82,
        category: "Одежда",
        type: "Юбки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Mossmore",
        fullname: "Юбка джинсовая",
        price: 7990,
        newprice: 4699,
        size: [40],
        colors: ["Черный", "Синий"],
      },
      {
        id: 83,
        category: "Одежда",
        type: "Юбки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Zarina",
        fullname: "Юбка",
        price: 1490,
        size: [40, 42, 44, 46, 48],
        colors: ["Розовый", "Зеленый", "Желтый"],
      },
      {
        id: 84,
        category: "Одежда",
        type: "Юбки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Nominee",
        fullname: "Юбка",
        price: 4999,
        newprice: 2999,
        size: [40, 44],
        colors: ["Синий", "Красный", "Розовый", "Зеленый", "Желтый"],
      },
      {
        id: 85,
        category: "Аксессуары",
        type: "Головные уборы",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Karl Lagerfeld",
        fullname: "Шапка IKONIK",
        price: 8900,
        newprice: 5990,
        colors: ["Черный", "Белый", "Серый", "Синий"],
      },
      {
        id: 86,
        category: "Аксессуары",
        type: "Головные уборы",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Patrizia Pepe",
        fullname: "Бейсболка",
        price: 5600,
        colors: ["Черный", "Белый", "Желтый"],
      },
      {
        id: 87,
        category: "Аксессуары",
        type: "Головные уборы",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Moschino",
        fullname: "Шапка",
        price: 9290,
        newprice: 6599,
        colors: ["Желтый"],
      },
      {
        id: 88,
        category: "Аксессуары",
        type: "Головные уборы",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Weekend Max Mara",
        fullname: "Шапка ALBEN",
        price: 11999,
        newprice: 8800,
        colors: ["Черный", "Белый", "Серый", "Синий"],
      },
      {
        id: 89,
        category: "Аксессуары",
        type: "Головные уборы",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Hugo",
        fullname: "Шапка",
        price: 6000,
        colors: ["Красный"],
      },
      {
        id: 90,
        category: "Аксессуары",
        type: "Зонты",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Karl Lagerfeld",
        fullname: "Зонт складной",
        price: 4500,
        colors: ["Черный"],
      },
      {
        id: 91,
        category: "Аксессуары",
        type: "Зонты",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Samsonite",
        fullname: "Зонт складной",
        price: 3500,
        colors: ["Черный"],
      },
      {
        id: 92,
        category: "Аксессуары",
        type: "Зонты",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Labbra",
        fullname: "Зонт складной",
        price: 3410,
        newprice: 1920,
        colors: ["Черный"],
      },
      {
        id: 93,
        category: "Аксессуары",
        type: "Канцелярские товары",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Parker",
        fullname: "Ручка",
        price: 3910,
        newprice: 2421,
        colors: ["Черный", "Белый"],
      },
      {
        id: 94,
        category: "Аксессуары",
        type: "Канцелярские товары",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Moleskine",
        fullname: "Блокнот CLASSIC Large",
        price: 1799,
        colors: [
          "Черный",
          "Белый",
          "Серый",
          "Синий",
          "Красный",
          "Розовый",
          "Зеленый",
          "Желтый",
        ],
      },
      {
        id: 95,
        category: "Аксессуары",
        type: "Канцелярские товары",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Deli",
        fullname: "Органайзер для хранения",
        price: 890,
        colors: [
          "Черный",
          "Белый",
          "Серый",
          "Синий",
          "Красный",
          "Розовый",
          "Зеленый",
          "Желтый",
        ],
      },
      {
        id: 96,
        category: "Аксессуары",
        type: "Рюкзаки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Karl Lagerfeld",
        fullname: "Рюкзак IKONIK",
        price: 33900,
        newprice: 17500,
        colors: ["Черный", "Белый"],
      },
      {
        id: 97,
        category: "Аксессуары",
        type: "Рюкзаки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Michael Michael Kors",
        fullname: "Рюкзак",
        price: 36900,
        colors: ["Белый"],
      },
      {
        id: 99,
        category: "Аксессуары",
        type: "Сумки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Karl Lagerfeld",
        fullname: "Сумка IKONIK",
        price: 7200,
        colors: ["Черный", "Белый"],
      },
      {
        id: 100,
        category: "Аксессуары",
        type: "Сумки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Tervolina",
        fullname: "Сумка",
        price: 17200,
        newprice: 10782,
        colors: ["Черный", "Белый"],
      },
      {
        id: 101,
        category: "Аксессуары",
        type: "Сумки",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Furla",
        fullname: "Сумка FURLA VARSITY STYLE",
        price: 43000,
        colors: ["Черный", "Белый"],
      },
      {
        id: 102,
        category: "Спорт",
        type: "Велоспорт",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Profit",
        fullname: "Тайтсы пуш-ап",
        price: 5490,
        newprice: 3290,
        size: [46, 48],
        colors: ["Черный", "Белый", "Серый"],
      },
      {
        id: 103,
        category: "Спорт",
        type: "Велоспорт",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Profit",
        fullname: "Топ",
        price: 2690,
        newprice: 2190,
        size: [44, 46, 48],
        colors: ["Черный", "Белый", "Серый", "Розовый", "Желтый"],
      },
      {
        id: 104,
        category: "Спорт",
        type: "Велоспорт",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Profit",
        fullname: "Тайтсы пуш-ап",
        price: 5490,
        newprice: 3290,
        size: [46, 48],
        colors: ["Черный", "Белый", "Красный", "Розовый"],
      },
      {
        id: 105,
        category: "Спорт",
        type: "Велоспорт",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Euphoria",
        fullname: "Шорты спортивные Classic",
        price: 4200,
        newprice: 2500,
        size: [40, 42, 44, 46, 48],
        colors: ["Черный", "Белый"],
      },
      {
        id: 106,
        category: "Спорт",
        type: "Велоспорт",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Gympanthers",
        fullname: "Велосипедки Gympanthers Original",
        price: 4200,
        size: [42],
        colors: ["Черный", "Белый"],
      },
      {
        id: 107,
        category: "Спорт",
        type: "Велоспорт",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Euphoria",
        fullname: "Леггинсы",
        price: 6799,
        newprice: 1380,
        size: [48],
        colors: ["Черный", "Белый", "Красный", "Розовый"],
      },
      {
        id: 108,
        category: "Спорт",
        type: "Скейтборд",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Roces",
        fullname: "Скейтборд Indian",
        price: 6299,
        colors: [
          "Черный",
          "Белый",
          "Серый",
          "Синий",
          "Красный",
          "Розовый",
          "Зеленый",
          "Желтый",
        ],
      },
      {
        id: 109,
        category: "Спорт",
        type: "Скейтборд",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Termit",
        fullname: "Скейтборд 22",
        price: 1199,
        colors: ["Черный", "Белый", "Серый", "Желтый"],
      },
      {
        id: 110,
        category: "Спорт",
        type: "Футбол",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Nike",
        fullname: "Мяч футбольный PL NK PTCH-FA19",
        price: 760,
        colors: ["Черный", "Белый"],
      },
      {
        id: 111,
        category: "Спорт",
        type: "Футбол",
        image_path: "/src/assets/images/product_photo.png",
        brand: "adidas",
        fullname: "Мяч футбольный CNXT21 TRN",
        price: 3100,
        newprice: 2499,
        colors: ["Черный", "Белый"],
      },
      {
        id: 112,
        category: "Спорт",
        type: "Футбол",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Molten",
        fullname: "Мяч футбольный",
        price: 3500,
        colors: ["Черный", "Белый", "Серый", "Синий", "Красный"],
      },
      {
        id: 113,
        category: "Спорт",
        type: "Фитнес",
        image_path: "/src/assets/images/product_photo.png",
        brand: "adidas",
        fullname: "Бутылка PERF BTTL 0,5",
        price: 650,
        colors: ["Розовый", "Зеленый", "Желтый"],
      },
      {
        id: 114,
        category: "Спорт",
        type: "Фитнес",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Prorun",
        fullname: "Гантели",
        price: 599,
        colors: ["Черный", "Белый", "Серый", "Синий", "Красный"],
      },
      {
        id: 115,
        category: "Красота",
        type: "Макияж",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Clarins",
        fullname: "Набор косметики",
        price: 2230,
        newprice: 1673,
      },
      {
        id: 116,
        category: "Красота",
        type: "Макияж",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Vivienne Sabo",
        fullname: "Тушь для ресниц",
        price: 560,
        newprice: 476,
      },
      {
        id: 117,
        category: "Красота",
        type: "Макияж",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Physicians Formula",
        fullname: "Палетка для лица",
        price: 2060,
      },
      {
        id: 118,
        category: "Красота",
        type: "Для ванны и душа",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Yves Rocher",
        fullname: "Гель для душа",
        price: 460,
      },
      {
        id: 119,
        category: "Красота",
        type: "Для ванны и душа",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Yves Rocher",
        fullname: "Гель для душа",
        price: 580,
      },
      {
        id: 120,
        category: "Красота",
        type: "Для ванны и душа",
        image_path: "/src/assets/images/product_photo.png",
        brand: "SeaCare",
        fullname: "Скраб",
        price: 2100,
        newprice: 1209,
      },
      {
        id: 121,
        category: "Красота",
        type: "Волосы",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Grace and Stella",
        fullname: "Набор для ухода за волосами",
        price: 3050,
        newprice: 1200,
      },
      {
        id: 122,
        category: "Красота",
        type: "Волосы",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Vichy",
        fullname: "Бальзам для волос",
        price: 1930,
        newprice: 1425,
      },
      {
        id: 123,
        category: "Красота",
        type: "Маникюр и педикюр",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Eveline Cosmetics",
        fullname: "Средство для укрепления ногтей",
        price: 270,
      },
      {
        id: 124,
        category: "Красота",
        type: "Маникюр и педикюр",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Anny",
        fullname: "Лак для ногтей",
        price: 640,
      },
      {
        id: 125,
        category: "Красота",
        type: "Маникюр и педикюр",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Olzori",
        fullname: "Пилка для педикюра",
        price: 1590,
        newprice: 990,
      },
      {
        id: 126,
        category: "Красота",
        type: "Маникюр и педикюр",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Metaleks",
        fullname: "Кусачки для маникюра",
        price: 1200,
      },
      {
        id: 127,
        category: "Красота",
        type: "Маникюр и педикюр",
        image_path: "/src/assets/images/product_photo.png",
        brand: "Victorinox",
        fullname: "Набор маникюрный",
        price: 7800,
        newprice: 5000,
      },
    ],
    favorites: [],
    basket: [],
  }),

  getters: {
    getProducts: (state) => {
      return (category, type) => {
        if (category === "" && type === "") {
          return state.products;
        }
        if (type === "") {
          return state.products.filter(
            (product) => product.category === category
          );
        }
        return state.products.filter(
          (product) => product.category === category && product.type === type
        );
      };
    },
    getBasketFullPrice() {
      return this.basket.reduce((total, product) => {
        return (total +=
          product.amount *
          (product?.newprice ? product.newprice : product.price));
      }, 0);
    },
    getBasketDiscount() {
      return this.basket.reduce((total, product) => {
        return (total += product.amount * product.price);
      }, 0);
    },
  },

  actions: {
    addFromLS(storageName) {
      if (storageName === "favorite-products" && downloadFromLS(storageName)) {
        this.favorites = downloadFromLS("favorite-products")
      }
      if (storageName === "basket-products" && downloadFromLS(storageName)) {
        this.basket = downloadFromLS("basket-products")
      }
    },
    switchFavorite(id) {
      this.products.forEach((product) => {
        if (product.id === id) {
          if (this.favorites.find((productF) => productF.id === id)) {
            this.favorites.splice(this.favorites.indexOf(product), 1);
            addItemLS("favorite-products", this.favorites);
          } else {
            this.favorites.push(product);
            addItemLS("favorite-products", this.favorites);
          }
        }
      });
    },
    addBasket(productOUT) {
      if (
        this.basket.find((productIN) => checkDuplicate(productIN, productOUT))
      ) {
        this.basket.find((productIN) =>
          checkDuplicate(productIN, productOUT)
        ).amount += 1;
        addItemLS("basket-products", this.basket);
      } else {
        this.basket.push(productOUT);
        addItemLS("basket-products", this.basket);
      }
    },
    removeBasket(productOUT) {
      this.basket = this.basket.filter(
        (productIN) => !checkDuplicate(productIN, productOUT)
      );
      addItemLS("basket-products", this.basket)
    },
    basketAmountAll() {
      return this.basket.reduce((amountSum, product) => {
        return (amountSum += product.amount);
      }, 0);
    },
    changeAmountProductBasket(productOUT, count) {
      this.basket.find((productIN) =>
        checkDuplicate(productIN, productOUT)
      ).amount = count;
      addItemLS("basket-products", this.basket)
    },
  },
});
